
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: postgres
        url: jdbc:postgresql://localhost:5432/eshipdiary
        username: postgres
    jpa:
#        show-sql: true
        hibernate:
#            ddl-auto: update
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL9Dialect
#                format_sql: ture
    data:
        rest:
            base-path: /api
server:
    session:
        cookie.max-age: 1800
        timeout: 1800

logging:
    level:
        org:
          springframework: INFO
#          hibernate.SQL: DEBUG
#          hibernate.type: TRACE
